name: Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment to remove AWS resources for?
        options:
          - staging
          - prod
  schedule:
    - cron: '0 * * * *' # Run every hour

jobs:
  destroy:
    name: Destroy ${{ matrix.environment }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        environment: ${{ github.event_name == 'schedule' && fromJson('["staging", "prod"]') || fromJson(format('["{0}"]', github.event.inputs.environment)) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform Destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export TF_WORKSPACE=${{ matrix.environment }}
          cd infra/
          docker compose run --rm terraform -chdir=deploy/ init
          docker compose run --rm terraform -chdir=deploy/ destroy -auto-approve
